export const ContentType = {
    BLOCKQUOTE: 'blockquote',
    BLANK: 'blank',
    BULLET_LIST: 'bulletList',
    BULLETED_LIST: 'bulletedList',
    CALLOUT_BOX: 'calloutBox',
    COLUMN: 'column',
    CODE: 'code',
    CODE_BLOCK: 'codeBlock',
    CUSTOM_BUTTON: 'customButton',
    DIVIDER: 'divider',
    HEADING_FOUR: 'heading4',
    HEADING_ONE: 'heading1',
    HEADING_THREE: 'heading3',
    HEADING_TWO: 'heading2',
    IMAGE: 'image',
    IMAGE_AND_TEXT: 'imageAndText',
    LINK: 'link',
    MULTI_COLUMN: 'multiColumn',
    NUMBERED_LIST: 'numberedList',
    PARAGRAPH: 'paragraph',
    QUOTE: 'quote',
    RESIZABLE_COLUMN: 'resizable-column',
    TABLE: 'table',
    TABLE_OF_CONTENTS: 'tableOfContents',
    TEXT: 'text',
    TITLE: 'title',
    TODO_LIST: 'todoList',
} as const

export type ContentType = (typeof ContentType)[keyof typeof ContentType]
